language: python
jdk: openjdk8
dist: trusty
sudo: false
cache:
  pip: true
python:
  - "3.6"
before_install:
  - mkdir -p /opt
  - wget -q -O /opt/spark.tgz http://www.gtlib.gatech.edu/pub/apache/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz
  - tar xzf /opt/spark.tgz -C /opt/
  - rm /opt/spark.tgz
  - export SPARK_HOME=/opt/spark-2.4.3-bin-hadoop2.7
  - export PATH=$PATH:/opt/spark-2.4.3-bin-hadoop2.7/bin
install:
  - pip install -r requirements.txt
script:
  - pytest