version: "3.1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: pdx
      POSTGRES_USER: pdx_admin
      POSTGRES_PASSWORD: pdx_admin
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-data:/var/lib/postgresql/data
    ports:
      - '5438:5432'

volumes:
  db-data:
