-- Rare Cancers. A list composed by different sources
insert into rare_cancers values ('acinic cell carcinoma');
insert into rare_cancers values ('acth-secreting tumor');
insert into rare_cancers values ('actinic keratosis');
insert into rare_cancers values ('acute erythroid leukemia');
insert into rare_cancers values ('acute lymphoblastic leukemia');
insert into rare_cancers values ('acute megakaryoblastic leukemia');
insert into rare_cancers values ('acute monocytic leukemia');
insert into rare_cancers values ('acute myeloblastic leukemia');
insert into rare_cancers values ('acute myelocytic leukemia');
insert into rare_cancers values ('acute myelogenous leukemia');
insert into rare_cancers values ('acute myelomonocytic leukemia');
insert into rare_cancers values ('acute non-lymphocytic leukemia');
insert into rare_cancers values ('acute promyelocytic leukemia');
insert into rare_cancers values ('adamantinoma');
insert into rare_cancers values ('adenoid cystic carcinoma');
insert into rare_cancers values ('alveolar soft part sarcoma');
insert into rare_cancers values ('ampullary cancer');
insert into rare_cancers values ('carcinoma of the ampulla of vater');
insert into rare_cancers values ('angiosarcoma');
insert into rare_cancers values ('appendix neuroendocrine tumor');
insert into rare_cancers values ('appendiceal carcinoid tumor');
insert into rare_cancers values ('askin tumor');
insert into rare_cancers values ('ewing sarcoma');
insert into rare_cancers values ('b-cell lymphoma');
insert into rare_cancers values ('barrett’s disease');
insert into rare_cancers values ('barrett’s esophagus');
insert into rare_cancers values ('bartholin gland cancer');
insert into rare_cancers values ('basaloid squamous cell carcinoma of the anus');
insert into rare_cancers values ('cloacogenic carcinoma');
insert into rare_cancers values ('bowen disease');
insert into rare_cancers values ('squamous cell carcinoma in situ');
insert into rare_cancers values ('bronchioloalveolar carcinoma');
insert into rare_cancers values ('adenocarcinoma in situ');
insert into rare_cancers values ('carcinoid tumor');
insert into rare_cancers values ('cardiac angiosarcoma');
insert into rare_cancers values ('castleman disease');
insert into rare_cancers values ('giant lymph node hyperplasia');
insert into rare_cancers values ('angiofollicular lymph node hyperplasia');
insert into rare_cancers values ('cholangiocarcinoma');
insert into rare_cancers values ('choriocarcinoma');
insert into rare_cancers values ('choroid plexus tumor');
insert into rare_cancers values ('chondrosarcoma');
insert into rare_cancers values ('chordoma');
insert into rare_cancers values ('chromophobe renal cell carcinoma');
insert into rare_cancers values ('chronic eosinophilic leukemia');
insert into rare_cancers values ('chronic neutrophilic leukemia');
insert into rare_cancers values ('clear cell sarcoma');
insert into rare_cancers values ('craniopharyngioma');
insert into rare_cancers values ('dermatofibrosarcoma protuberans');
insert into rare_cancers values ('desmoid tumor');
insert into rare_cancers values ('fibromatosis');
insert into rare_cancers values ('desmoplastic small round cell tumor');
insert into rare_cancers values ('dysgerminoma');
insert into rare_cancers values ('embryonal carcinoma');
insert into rare_cancers values ('endodermal sinus tumor');
insert into rare_cancers values ('yolk sac tumor');
insert into rare_cancers values ('endometrial stromal sarcoma');
insert into rare_cancers values ('ependymoma');
insert into rare_cancers values ('epithelial appendix cancer');
insert into rare_cancers values ('epithelial appendiceal cancer');
insert into rare_cancers values ('epithelial-myoepithelial carcinoma');
insert into rare_cancers values ('epithelioid hemangioendothelioma (ehe)');
insert into rare_cancers values ('epithelioid sarcoma');
insert into rare_cancers values ('essential thrombocythemia');
insert into rare_cancers values ('esthesioneuroblastoma');
insert into rare_cancers values ('olfactory neuroblastoma');
insert into rare_cancers values ('extra-cranial malignant rhabdoid tumor (mrt)');
insert into rare_cancers values ('extranodal nk/t-cell lymphoma, nasal type');
insert into rare_cancers values ('fallopian tube cancer');
insert into rare_cancers values ('fibrolamellar carcinoma');
insert into rare_cancers values ('fibromyxoid sarcoma');
insert into rare_cancers values ('evans’ tumor');
insert into rare_cancers values ('fibrosarcoma');
insert into rare_cancers values ('folliculotropic mycosis fungoides');
insert into rare_cancers values ('ganglioglioma');
insert into rare_cancers values ('ganglioneuroblastoma');
insert into rare_cancers values ('gastric adenocarcinoma and proximal polyposis of the stomach (gapps)');
insert into rare_cancers values ('gastrinoma');
insert into rare_cancers values ('gastroesophageal junction (gej) cancer');
insert into rare_cancers values ('gestational trophoblastic disease (gtd)');
insert into rare_cancers values ('hydatidiform mole');
insert into rare_cancers values ('gestational trophoblastic neoplasia');
insert into rare_cancers values ('germ cell tumor');
insert into rare_cancers values ('giant cell tumor of bone');
insert into rare_cancers values ('glucagonoma');
insert into rare_cancers values ('granulomatous slack skin');
insert into rare_cancers values ('hairy cell leukemia');
insert into rare_cancers values ('heart cancer');
insert into rare_cancers values ('hemangioendothelioma');
insert into rare_cancers values ('hemangiosarcoma');
insert into rare_cancers values ('hepatobiliary cancer');
insert into rare_cancers values ('hepatoblastoma');
insert into rare_cancers values ('hepatocellular carcinoma');
insert into rare_cancers values ('hepatoma');
insert into rare_cancers values ('hereditary diffuse gastric cancer (hdgc)');
insert into rare_cancers values ('hurthle cell cancer');
insert into rare_cancers values ('oxyphil cell carcinoma');
insert into rare_cancers values ('insulinoma');
insert into rare_cancers values ('islet cell tumor');
insert into rare_cancers values ('keratoacanthoma');
insert into rare_cancers values ('klatskin tumor');
insert into rare_cancers values ('large cell neuroendocrine carcinoma (lcnec)');
insert into rare_cancers values ('large granular lymphocyte (lgl) leukemia');
insert into rare_cancers values ('leiomyosarcoma');
insert into rare_cancers values ('leydig cell tumor');
insert into rare_cancers values ('lip cancer');
insert into rare_cancers values ('liposarcoma');
insert into rare_cancers values ('lymphomatoid papulosis');
insert into rare_cancers values ('lymphoplasmacytic lymphoma');
insert into rare_cancers values ('malignant mesenchymoma');
insert into rare_cancers values ('malignant mixed mullerian tumor');
insert into rare_cancers values ('malignant mixed mesodermal tumor');
insert into rare_cancers values ('uterine carcinosarcoma');
insert into rare_cancers values ('malignant peripheral nerve sheath tumor (mpnst)');
insert into rare_cancers values ('malignant rhabdoid tumor of the kidney');
insert into rare_cancers values ('medulloepithelioma');
insert into rare_cancers values ('meningioma');
insert into rare_cancers values ('mesoblastic nephroma');
insert into rare_cancers values ('metaplastic cancer of the breast');
insert into rare_cancers values ('monoclonal gammopathy of undetermined significance (mgus)');
insert into rare_cancers values ('mouth cancer');
insert into rare_cancers values ('mucinous cystic neoplasm');
insert into rare_cancers values ('mucoepidermoid carcinoma');
insert into rare_cancers values ('muscle cancer');
insert into rare_cancers values ('myosarcoma');
insert into rare_cancers values ('myoepithelial carcinoma');
insert into rare_cancers values ('mycosis fungoides');
insert into rare_cancers values ('myelofibrosis');
insert into rare_cancers values ('myxofibrosarcoma');
insert into rare_cancers values ('nephroblastoma');
insert into rare_cancers values ('neuroendocrine carcinoma of the skin');
insert into rare_cancers values ('nut carcinoma');
insert into rare_cancers values ('oat cell cancer');
insert into rare_cancers values ('occult primary cancer');
insert into rare_cancers values ('ocular melanoma');
insert into rare_cancers values ('intraocular melanoma');
insert into rare_cancers values ('uveal melanoma');
insert into rare_cancers values ('conjunctival melanoma');
insert into rare_cancers values ('orbital melanoma');
insert into rare_cancers values ('adnexal melanoma');
insert into rare_cancers values ('oligodendroglioma');
insert into rare_cancers values ('oncocytic carcinoma');
insert into rare_cancers values ('ovarian small cell cancer');
insert into rare_cancers values ('paget disease');
insert into rare_cancers values ('pagetoid reticulosis');
insert into rare_cancers values ('paraganglioma');
insert into rare_cancers values ('extra-adrenal pheochromocytoma');
insert into rare_cancers values ('parathyroid cancer');
insert into rare_cancers values ('periosteal osteosarcoma');
insert into rare_cancers values ('peripheral primitive neuroectodermal tumor (ppnet)');
insert into rare_cancers values ('pheochromocytoma');
insert into rare_cancers values ('phyllodes tumor');
insert into rare_cancers values ('pineoblastoma');
insert into rare_cancers values ('plasmacytoma');
insert into rare_cancers values ('polycythemia vera');
insert into rare_cancers values ('polymorphous low-grade adenocarcinoma');
insert into rare_cancers values ('primary cutaneous lymphoma');
insert into rare_cancers values ('primary peritoneal carcinoma');
insert into rare_cancers values ('prolactinoma');
insert into rare_cancers values ('lactotroph adenoma');
insert into rare_cancers values ('prolymphocytic leukemia');
insert into rare_cancers values ('renal cell carcinoma');
insert into rare_cancers values ('sarcomatoid carcinoma');
insert into rare_cancers values ('sarcomatoid carcinosarcoma');
insert into rare_cancers values ('schwannoma');
insert into rare_cancers values ('sclerosing epithelioid fibrosarcoma');
insert into rare_cancers values ('sebaceous carcinoma');
insert into rare_cancers values ('seminoma');
insert into rare_cancers values ('sertoli cell tumor');
insert into rare_cancers values ('sezary syndrome');
insert into rare_cancers values ('sinus cancer');
insert into rare_cancers values ('skin adnexal tumors');
insert into rare_cancers values ('solid pseudopapillary neoplasm');
insert into rare_cancers values ('solitary fibrous tumor');
insert into rare_cancers values ('solitary plasmacytoma');
insert into rare_cancers values ('somatostatinoma');
insert into rare_cancers values ('spermatocytic seminoma');
insert into rare_cancers values ('spindle cell neoplasm');
insert into rare_cancers values ('spindle cell tumor');
insert into rare_cancers values ('spindle cell carcinoma');
insert into rare_cancers values ('spindle cell sarcoma');
insert into rare_cancers values ('subcutaneous panniculitis-like t-cell lymphoma');
insert into rare_cancers values ('synovial sarcoma');
insert into rare_cancers values ('t-cell lymphoma');
insert into rare_cancers values ('teratoma');
insert into rare_cancers values ('throat cancer');
insert into rare_cancers values ('thymoma');
insert into rare_cancers values ('tongue cancer');
insert into rare_cancers values ('tonsil cancer');
insert into rare_cancers values ('trabecular cancer');
insert into rare_cancers values ('translocation renal cell carcinoma');
insert into rare_cancers values ('transitional cell carcinoma');
insert into rare_cancers values ('urothelial carcinoma');
insert into rare_cancers values ('undifferentiated pleomorphic sarcoma');
insert into rare_cancers values ('malignant fibrous histiocytoma');
insert into rare_cancers values ('urachal cancer');
insert into rare_cancers values ('urethral cancer');
insert into rare_cancers values ('uterine cancer');
insert into rare_cancers values ('verrucous carcinoma');
insert into rare_cancers values ('vipoma');
insert into rare_cancers values ('vocal cord/voice box cancer');
insert into rare_cancers values ('womb cancer');
insert into rare_cancers values ('infantile embryonal cancer');
insert into rare_cancers values ('childhood liposarcoma');
insert into rare_cancers values ('childhood malignant testicular germ cell tumor');
insert into rare_cancers values ('childhood meningeal melanoma');
insert into rare_cancers values ('childhood neuroblastoma');
insert into rare_cancers values ('childhood osteosarcoma');
insert into rare_cancers values ('childhood rhabdomyosarcoma');
insert into rare_cancers values ('childhood soft tissue sarcoma');
insert into rare_cancers values ('childhood synovial sarcoma');