class Constants:
    RAW_DIRECTORY = "raw"
    TRANSFORMED_DIRECTORY = "transformed"
    DATABASE_FORMATTED = "database_formatted"

    # File ids names
    PLATFORM_SAMPLE_MODULE = "sampleplatform"
    PATIENT_MODULE = "patient"
    SAMPLE_MODULE = "sample"
    SHARING_MODULE = "sharing"
    LOADER_MODULE = "loader"
    MODEL_MODULE = "model"
    MODEL_VALIDATION_MODULE = "model_validation"

    DATA_SOURCE_COLUMN = "data_source_tmp"

    # Entities names
    DIAGNOSIS_ENTITY = "diagnosis"
    ETHNICITY_ENTITY = "ethnicity"
    MODEL_ENTITY = "model"
    CONTACT_PEOPLE_ENTITY = "contact_people"
    CONTACT_FORM_ENTITY = "contact_form"
    SOURCE_DATABASE_ENTITY = "source_database"
    QUALITY_ASSURANCE_ENTITY = "quality_assurance"
    PATIENT_ENTITY = "patient"
    PROVIDER_GROUP_ENTITY = "provider_group"
    PROVIDER_TYPE_ENTITY = "provider_type"
    PUBLICATION_GROUP_ENTITY = "publication_group"
    TISSUE_ENTITY = "tissue"
    TUMOUR_TYPE_ENTITY = "tumour_type"
    PATIENT_SAMPLE_ENTITY = "patient_sample"
    XENOGRAFT_SAMPLE_ENTITY = "xenograft_sample"
    PATIENT_SNAPSHOT_ENTITY = "patient_snapshot"
    ENGRAFTMENT_SITE_ENTITY = "engraftment_site"
    ENGRAFTMENT_TYPE_ENTITY = "engraftment_type"
    ENGRAFTMENT_MATERIAL_ENTITY = "engraftment_material"
    ENGRAFTMENT_SAMPLE_STATE_ENTITY = "engraftment_sample_state"
    ENGRAFTMENT_SAMPLE_TYPE_ENTITY = "engraftment_sample_type"
    ACCESSIBILITY_GROUP_ENTITY = "accessibility_group"
    HOST_STRAIN_ENTITY = "host_strain"
    PROJECT_GROUP_ENTITY = "project_group"
