facet_definitions = [
    {
        "facet_section": "search",
        "facet_name": "Search",
        "facet_column": "search_terms",
        "facet_example": "Melanoma",
        "any_operator": "ov",
        "all_operator": "",
        "is_boolean": False,
        "facet_type": "",
        "dynamic_values": True
    },
    {
        "facet_section": "model",
        "facet_name": "Dataset available",
        "facet_column": "dataset_available",
        "facet_example": '""',
        "any_operator": "ov",
        "all_operator": "",
        "is_boolean": False,
        "facet_type": "check",
        "dynamic_values": True
    },
    {
        "facet_section": "model",
        "facet_name": "Datasource",
        "facet_column": "data_source",
        "facet_example": '""',
        "any_operator": "in",
        "all_operator": "",
        "is_boolean": False,
        "facet_type": "check",
        "dynamic_values": True
    },
    {
        "facet_section": "model",
        "facet_name": "Type",
        "facet_column": "model_type",
        "facet_example": '""',
        "any_operator": "in",
        "all_operator": "",
        "is_boolean": False,
        "facet_type": "check",
        "dynamic_values": True
    },
    {
        "facet_section": "model",
        "facet_name": "Model ID",
        "facet_column": "external_model_id",
        "facet_example": "TM00015",
        "any_operator": "in",
        "all_operator": "",
        "is_boolean": False,
        "facet_type": "autocomplete",
        "dynamic_values": True
    },
    {
        "facet_section": "model",
        "facet_name": "Project",
        "facet_column": "project_name",
        "facet_example": '""',
        "any_operator": "in",
        "all_operator": "",
        "is_boolean": False,
        "facet_type": "check",
        "dynamic_values": True
    },
    {
        "facet_section": "model",
        "facet_name": "Related Models",
        "facet_column": "has_relations",
        "facet_example": '""',
        "any_operator": "in",
        "all_operator": "",
        "is_boolean": True,
        "facet_options": ["related models=true"],
        "facet_type": "check",
        "dynamic_values": False
    },
     {
        "facet_section": "model",
        "facet_name": "Paediatric",
        "facet_column": "paediatric",
        "facet_example": '""',
        "any_operator": "in",
        "all_operator": "",
        "is_boolean": True,
        "facet_options": ["paediatric=true"],
        "facet_type": "check",
        "dynamic_values": False
    },
    {
        "facet_section": "molecular_data",
        "facet_name": "Gene mutation",
        "facet_column": "markers_with_mutation_data",
        "facet_example": "RTP3",
        "any_operator": "ov",
        "all_operator": "cs",
        "is_boolean": False,
        "facet_type": "multivalued",
        "dynamic_values": True
    },
    {
        "facet_section": "molecular_data",
        "facet_name": "Copy Number Alteration",
        "facet_column": "markers_with_cna_data",
        "facet_example": "RTP3",
        "any_operator": "ov",
        "all_operator": "cs",
        "is_boolean": False,
        "facet_type": "multivalued",
        "dynamic_values": True
    },
    {
        "facet_section": "molecular_data",
        "facet_name": "Gene Expression",
        "facet_column": "markers_with_expression_data",
        "facet_example": "BEST1",
        "any_operator": "ov",
        "all_operator": "cs",
        "is_boolean": False,
        "facet_type": "multivalued",
        "dynamic_values": True
    },
    {
        "facet_section": "molecular_data",
        "facet_name": "Breast cancer biomarkers",
        "facet_column": "breast_cancer_biomarkers",
        "facet_example": '""',
        "any_operator": "ov",
        "all_operator": "cs",
        "is_boolean": False,
        "facet_type": "check",
        "dynamic_values": True
    },
    {
        "facet_section": "molecular_data",
        "facet_name": "Bio markers",
        "facet_column": "markers_with_biomarker_data",
        "facet_example": "ESR1",
        "any_operator": "ov",
        "all_operator": "cs",
        "is_boolean": False,
        "facet_type": "multivalued",
        "dynamic_values": True
    },
    {
        "facet_section": "molecular_data",
        "facet_name": "MSI Status",
        "facet_column": "msi_status",
        "facet_example": "Stable",
        "any_operator": "ov",
        "all_operator": "",
        "is_boolean": False,
        "facet_type": "check",
        "dynamic_values": True
    },
    {
        "facet_section": "molecular_data",
        "facet_name": "HLA types",
        "facet_column": "hla_types",
        "facet_example": "HLA-A",
        "any_operator": "ov",
        "all_operator": "",
        "is_boolean": False,
        "facet_type": "check",
        "dynamic_values": True
    },
    {
        "facet_section": "treatment_drug_dosing",
        "facet_name": "Treatment type",
        "facet_column": "custom_treatment_type_list",
        "facet_example": '""',
        "any_operator": "ov",
        "all_operator": "cs",
        "is_boolean": False,
        "facet_type": "multivalued",
        "dynamic_values": True
    },
    {
        "facet_section": "treatment_drug_dosing",
        "facet_name": "Patient treatment",
        "facet_column": "treatment_list",
        "facet_example": "radiation therapy",
        "any_operator": "ov",
        "all_operator": "cs",
        "is_boolean": False,
        "facet_type": "multivalued",
        "dynamic_values": True
    },
    {
        "facet_section": "treatment_drug_dosing",
        "facet_name": "Model dosing",
        "facet_column": "model_treatment_list",
        "facet_example": "cyclophosphamide",
        "any_operator": "ov",
        "all_operator": "cs",
        "is_boolean": False,
        "facet_type": "multivalued",
        "dynamic_values": True
    },
    {
        "facet_section": "patient_tumour",
        "facet_name": "Tumour type",
        "facet_column": "tumour_type",
        "facet_example": '""',
        "remove_invalid_values": True,
        "any_operator": "in",
        "all_operator": "",
        "is_boolean": False,
        "facet_type": "check",
        "dynamic_values": True
    },
    {
        "facet_section": "patient_tumour",
        "facet_name": "Patient sex",
        "facet_column": "patient_sex",
        "facet_example": '""',
        "any_operator": "in",
        "all_operator": "",
        "is_boolean": False,
        "facet_type": "check",
        "dynamic_values": True
    },
    {
        "facet_section": "patient_tumour",
        "facet_name": "Patient Ethnicity",
        "facet_column": "patient_ethnicity",
        "facet_example": '""',
        "any_operator": "in",
        "all_operator": "",
        "is_boolean": False,
        "facet_type": "check",
        "dynamic_values": True
    },
    {
        "facet_section": "patient_tumour",
        "facet_name": "Patient age",
        "facet_column": "patient_age",
        "facet_example": '""',
        "any_operator": "in",
        "all_operator": "",
        "is_boolean": False,
        "facet_type": "check",
        "dynamic_values": True
    },
    {
        "facet_section": "patient_tumour",
        "facet_name": "Cancer system",
        "facet_column": "cancer_system",
        "facet_example": '""',
        "any_operator": "in",
        "all_operator": "",
        "is_boolean": False,
        "facet_type": "check",
        "dynamic_values": True
    },
    {
        "facet_section": "patient_tumour",
        "facet_name": "Collection Site",
        "facet_column": "collection_site",
        "facet_example": '""',
        "any_operator": "in",
        "all_operator": "",
        "is_boolean": False,
        "facet_type": "check",
        "dynamic_values": True
    },
    {
        "facet_section": "patient_tumour",
        "facet_name": "Primary Site",
        "facet_column": "primary_site",
        "facet_example": '""',
        "any_operator": "in",
        "all_operator": "",
        "is_boolean": False,
        "facet_type": "check",
        "dynamic_values": True
    }
]