groups:
  - group: "metadata"
    modules:
      - name: "source"
        type: "yaml"
        name_patterns: [ "web/$provider_source.yaml" ]
        columns:
          - "provider_name"
          - "provider_abbreviation"
          - "provider_type"
          - "project"
          - "provider_page_title"
          - "provider_description"
          - "pdcm_resource_description"

      - name: "model"
        type: "tsv"
        name_patterns: ["$provider_metadata-pdx_model.tsv"]
        columns:
          - "model_id"
          - "host_strain_name"
          - "host_strain_nomenclature"
          - "engraftment_site"
          - "engraftment_type"
          - "sample_type"
          - "sample_state"
          - "passage_number"
          - "publications"

      - name: "cell-model"
        type: "tsv"
        name_patterns: [ "$provider_metadata-cell_model.tsv" ]
        columns:
          - "model_id"
          - "name"
          - "type"
          - "growth_properties"
          - "parent_id"
          - "origin_patient_sample_id"
          - "comments"
          - "external_ids"
          - "supplier"
          - "publications"

      - name: "model_validation"
        type: "tsv"
        name_patterns: ["$provider_metadata-model_validation.tsv"]
        columns:
          - "model_id"
          - "validation_technique"
          - "description"
          - "passages_tested"
          - "validation_host_strain_nomenclature"

      - name: "patient"
        type: "tsv"
        name_patterns: ["$provider_metadata-patient.tsv"]
        columns:
          - "patient_id"
          - "sex"
          - "history"
          - "ethnicity"
          - "ethnicity_assessment_method"
          - "initial_diagnosis"
          - "age_at_initial_diagnosis"

      - name: "sample"
        type: "tsv"
        name_patterns: ["$provider_metadata-patient_sample.tsv"]
        columns:
          - "patient_id"
          - "sample_id"
          - "collection_date"
          - "collection_event"
          - "months_since_collection_1"
          - "age_in_years_at_collection"
          - "diagnosis"
          - "tumour_type"
          - "primary_site"
          - "collection_site"
          - "stage"
          - "staging_system"
          - "grade"
          - "grading_system"
          - "virology_status"
          - "sharable"
          - "treatment_naive_at_collection"
          - "treated_at_collection"
          - "treated_prior_to_collection"
          - "model_id"

      - name: "sharing"
        type: "tsv"
        name_patterns: ["$provider_metadata-sharing.tsv"]
        columns:
          - "model_id"
          - "accessibility"
          - "europdx_access_modality"
          - "email"
          - "name"
          - "form_url"
          - "database_url"
          - "license"

      - name: "drug-dosing"
        type: "tsv"
        name_patterns: [ "drug/$provider_drugdosing*.tsv" ]
        columns:
          - "model_id"
          - "passage_range"
          - "treatment_name"
          - "treatment_type"
          - "treatment_dose"
          - "administration_route"
          - "treatment_schedule"
          - "treatment_length"
          - "treatment_response"
          - "response_classification"

      - name: "patient-treatment"
        type: "tsv"
        name_patterns: [ "treatment/$provider_patienttreatment*.tsv" ]
        columns:
          - "patient_id"
          - "treatment_name"
          - "treatment_dose"
          - "treatment_starting_date"
          - "treatment_duration"
          - "treatment_event"
          - "elapsed_time"
          - "treatment_response"
          - "response_classification"
          - "model_id"

  - group: "molecular-metadata"
    modules:
      - name: "molchar_sample"
        type: "tsv"
        name_patterns: [ "$provider_molecular_metadata-sample.tsv" ]
        columns:
          - "model_id"
          - "sample_id"
          - "sample_origin"
          - "passage"
          - "host_strain_name"
          - "host_strain_nomenclature"
          - "engrafted_tumor_collection_site"
          - "raw_data_url"
          - "platform_id"

      - name: "molchar_platform"
        type: "tsv"
        name_patterns: [ "$provider_molecular_metadata-platform.tsv" ]
        columns:
          - "platform_id"
          - "molecular_characterisation_type"
          - "instrument_model"
          - "library_strategy"
          - "library_selection"
          - "library_notes"
          - "genome_assembly"

      - name: "molchar_platform_web"
        type: "tsv"
        name_patterns: [ "$provider_molecular_metadata-platform_web.tsv" ]
        columns:
          - "platform_id"
          - "molecular_methods_description"
          - "analysis_description"


  - group: "molecular-data"
    modules:
      - name: "cna"
        type: "tsv"
        name_patterns: ["cna/$provider_cna*.tsv", "cna/*/$provider_cna*.tsv"]
        columns:
          - "sample_id"
          - "chromosome"
          - "strand"
          - "seq_start_position"
          - "seq_end_position"
          - "symbol"
          - "ucsc_gene_id"
          - "ncbi_gene_id"
          - "ensembl_gene_id"
          - "log10r_cna"
          - "log2r_cna"
          - "copy_number_status"
          - "gistic_value"
          - "picnic_value"
          - "platform_id"

      - name: "cyto"
        type: "tsv"
        name_patterns: ["cyto/$provider_cyto*.tsv"]
        columns:
          - "sample_id"
          - "symbol"
          - "marker_status"
          - "essential_or_additional_marker"
          - "platform_id"

      - name: "expression"
        type: "tsv"
        name_patterns: ["expression/$provider_expression*.tsv", "expression/*/$provider_expression*.tsv"]
        columns:
          - "sample_id"
          - "chromosome"
          - "strand"
          - "seq_start_position"
          - "seq_end_position"
          - "symbol"
          - "ucsc_gene_id"
          - "ensembl_gene_id"
          - "ncbi_gene_id"
          - "rnaseq_coverage"
          - "rnaseq_fpkm"
          - "rnaseq_tpm"
          - "rnaseq_count"
          - "affy_hgea_probe_id"
          - "affy_hgea_expression_value"
          - "illumina_hgea_probe_id"
          - "illumina_hgea_expression_value"
          - "z_score"
          - "platform_id"

      - name: "mutation"
        type: "tsv"
        name_patterns: [ "mut/$provider_mut*.tsv", "mut/*/$provider_mut*.tsv" ]
        columns:
          - "sample_id"
          - "symbol"
          - "biotype"
          - "coding_sequence_change"
          - "variant_class"
          - "codon_change"
          - "amino_acid_change"
          - "consequence"
          - "functional_prediction"
          - "read_depth"
          - "allele_frequency"
          - "chromosome"
          - "strand"
          - "seq_start_position"
          - "ref_allele"
          - "alt_allele"
          - "ucsc_gene_id"
          - "ncbi_gene_id"
          - "ncbi_transcript_id"
          - "ensembl_gene_id"
          - "ensembl_transcript_id"
          - "variation_id"
          - "platform_id"





