groups:
  - group: "metadata"
    files:
      - id: "model"
        name_pattern: "*metadata-model.tsv"
        columns:
          - "model_id"
          - "host_strain_name"
          - "host_strain_nomenclature"
          - "engraftment_site"
          - "engraftment_type"
          - "sample_type"
          - "sample_state"
          - "passage_number"
          - "publications"

      - id: "model_validation"
        name_pattern: "*metadata-model_validation.tsv"
        columns:
          - "model_id"
          - "validation_technique"
          - "description"
          - "passages_tested"
          - "validation_host_strain_nomenclature"

      - id: "patient"
        name_pattern: "*metadata-patient.tsv"
        columns:
          - "patient_id"
          - "sex"
          - "history"
          - "ethnicity"
          - "ethnicity_assessment_method"
          - "initial_diagnosis"
          - "age_at_initial_diagnosis"

      - id: "sample"
        name_pattern: "*metadata-sample.tsv"
        columns:
          - "patient_id"
          - "sample_id"
          - "collection_date"
          - "collection_event"
          - "months_since_collection_1"
          - "age_in_years_at_collection"
          - "diagnosis"
          - "tumour_type"
          - "primary_site"
          - "collection_site"
          - "stage"
          - "staging_system"
          - "grade"
          - "grading_system"
          - "virology_status"
          - "sharable"
          - "treatment_naive_at_collection"
          - "treated"
          - "prior_treatment"
          - "model_id"

      - id: "sharing"
        name_pattern: "*metadata-sharing.tsv"
        columns:
          - "model_id"
          - "provider_type"
          - "accessibility"
          - "europdx_access_modality"
          - "email"
          - "name"
          - "form_url"
          - "database_url"
          - "provider_name"
          - "provider_abbreviation"
          - "project"

      - id: "loader"
        name_pattern: "*metadata-loader.tsv"
        columns:
          - "name"
          - "abbreviation"
          - "internal_url"
          - "internal_dosing_url"

  - group: "treatment"
    files:
      - id: "drug-dosing"
        name_pattern: "drug/*drugdosing-Sheet1.tsv"
        columns:
          - "abbreviation"
          - "model_id"
          - "passage_range"
          - "treatment_name"
          - "treatment_type"
          - "treatment_dose"
          - "administration_route"
          - "treatment_schedule"
          - "treatment_length"
          - "treatment_response"
          - "response_classification"
          - "analysis_protocol"
          - "raw_data_access"
          - "raw_data_file"
          - "internal_treatment_url"

      - id: "patient-treatment"
        name_pattern: "treatment/*patienttreatment-Sheet1.tsv"
        columns:
          - "patient_id"
          - "treatment_name"
          - "treatment_dose"
          - "treatment_starting_date"
          - "treatment_duration"
          - "treatment_event"
          - "elapsed_time"
          - "treatment_response"
          - "response_classification"

  - group: "sampleplatform"
    files:
      - id: "sampleplatform"
        name_pattern: "*sampleplatform-data.tsv"
        columns:
          - "sample_id"
          - "model_id"
          - "sample_origin"
          - "raw_data_file"
          - "platform"
          - "platform_type"

  - group: "molecular-data"
    skip: False
    files:
      - id: "cna"
        name_pattern: "cna/*cna*.tsv"
        columns:
          - "model_id"
          - "sample_id"
          - "sample_origin"
          - "passage"
          - "host_strain_nomenclature"
          - "chromosome"
          - "seq_start_position"
          - "seq_end_position"
          - "symbol"
          - "ucsc_gene_id"
          - "ncbi_gene_id"
          - "ensembl_gene_id"
          - "log10r_cna"
          - "log2r_cna"
          - "copy_number_status"
          - "gistic_value"
          - "picnic_value"
          - "genome_assembly"
          - "platform"



