groups:
  - group: "metadata"
    modules:
      - name: "model"
        name_patterns: ["$provider_metadata-pdx_models.tsv"]
        columns:
          - "model_id"
          - "host_strain_name"
          - "host_strain_nomenclature"
          - "engraftment_site"
          - "engraftment_type"
          - "sample_type"
          - "sample_state"
          - "passage_number"
          - "publications"

      - name: "model_validation"
        name_patterns: ["$provider_metadata-model_validation.tsv"]
        columns:
          - "model_id"
          - "validation_technique"
          - "description"
          - "passages_tested"
          - "validation_host_strain_nomenclature"

      - name: "patient"
        name_patterns: ["$provider_metadata-patient.tsv"]
        columns:
          - "patient_id"
          - "sex"
          - "history"
          - "ethnicity"
          - "ethnicity_assessment_method"
          - "initial_diagnosis"
          - "age_at_initial_diagnosis"

      - name: "sample"
        name_patterns: ["$provider_metadata-sample.tsv"]
        columns:
          - "patient_id"
          - "sample_id"
          - "collection_date"
          - "collection_event"
          - "months_since_collection_1"
          - "age_in_years_at_collection"
          - "diagnosis"
          - "tumour_type"
          - "primary_site"
          - "collection_site"
          - "stage"
          - "staging_system"
          - "grade"
          - "grading_system"
          - "virology_status"
          - "sharable"
          - "treatment_naive_at_collection"
          - "treated"
          - "prior_treatment"
          - "model_id"

      - name: "sharing"
        name_patterns: ["$provider_metadata-sharing.tsv"]
        columns:
          - "model_id"
          - "provider_type"
          - "accessibility"
          - "europdx_access_modality"
          - "email"
          - "name"
          - "form_url"
          - "database_url"
          - "provider_name"
          - "provider_abbreviation"
          - "project"

      - name: "drug-dosing"
        name_patterns: [ "drug/$provider_drugdosing-Sheet1.tsv" ]
        columns:
          - "abbreviation"
          - "model_id"
          - "passage_range"
          - "treatment_name"
          - "treatment_type"
          - "treatment_dose"
          - "administration_route"
          - "treatment_schedule"
          - "treatment_length"
          - "treatment_response"
          - "response_classification"
          - "analysis_protocol"
          - "raw_data_access"
          - "raw_data_file"
          - "internal_treatment_url"

      - name: "patient-treatment"
        name_patterns: [ "treatment/$provider_patienttreatment-Sheet1.tsv" ]
        columns:
          - "patient_id"
          - "treatment_name"
          - "treatment_dose"
          - "treatment_starting_date"
          - "treatment_duration"
          - "treatment_event"
          - "elapsed_time"
          - "treatment_response"
          - "response_classification"

  - group: "molecular-metadata"
    modules:
      - name: "molchar_sample"
        name_patterns: [ "$provider_molecular_metadata-sample.tsv" ]
        columns:
          - "model_id"
          - "sample_id"
          - "sample_origin"
          - "passage"
          - "host_strain_name"
          - "host_strain_nomenclature"
          - "engrafted_tumor_collection_site"
          - "raw_data_url"
          - "platform_id"

      - name: "molchar_platform"
        name_patterns: [ "$provider_molecular_metadata-platform.tsv" ]
        columns:
          - "platform_id"
          - "molecular_characterisation_type"
          - "instrument_model"
          - "library_strategy"
          - "library_selection"
          - "library_notes"
          - "genome_assembly"

      - name: "molchar_platform_web"
        name_patterns: [ "$provider_molecular_metadata-platform_web.tsv" ]
        columns:
          - "platform_id"
          - "molecular_methods_description"
          - "analysis_description"


  - group: "molecular-data"
    modules:
      - name: "cna"
        name_patterns: ["cna/$provider_cna*.tsv"]
        columns:
          - "sample_id"
          - "chromosome"
          - "seq_start_position"
          - "seq_end_position"
          - "symbol"
          - "ucsc_gene_id"
          - "ncbi_gene_id"
          - "ensembl_gene_id"
          - "log10r_cna"
          - "log2r_cna"
          - "copy_number_status"
          - "gistic_value"
          - "picnic_value"
          - "genome_assembly"
          - "platform"

      - name: "cyto"
        name_patterns: ["cyto/$provider_cyto*.tsv"]
        columns:
          - "sample_id"
          - "symbol"
          - "marker_status"
          - "essential_or_additional_marker"
          - "platform"
          - "protocol_file_name"
          - "result_file_name"

      - name: "expression"
        name_patterns: ["expression/$provider_expression*.tsv", "expression/*/$provider_expression*.tsv"]
        columns:
          - "sample_id"
          - "chromosome"
          - "strand"
          - "seq_start_position"
          - "seq_end_position"
          - "symbol"
          - "ucsc_gene_id"
          - "ensembl_gene_id"
          - "rnaseq_coverage"
          - "rnaseq_fpkm"
          - "rnaseq_tpm"
          - "rnaseq_count"
          - "affy_hgea_probe_id"
          - "affy_hgea_expression_value"
          - "illumina_hgea_probe_id"
          - "illumina_hgea_expression_value"
          - "z_score"
          - "genome_assembly"
          - "platform"

      - name: "mutation"
        name_patterns: [ "mut/$provider_mut*.tsv", "mut/*/$provider_mut*.tsv" ]
        columns:
          - "sample_id"
          - "symbol"
          - "biotype"
          - "coding_sequence_change"
          - "variant_class"
          - "codon_change"
          - "amino_acid_change"
          - "consequence"
          - "functional_prediction"
          - "read_depth"
          - "allele_frequency"
          - "chromosome"
          - "seq_start_position"
          - "ref_allele"
          - "alt_allele"
          - "ucsc_gene_id"
          - "ncbi_gene_id"
          - "ncbi_transcript_id"
          - "ensembl_gene_id"
          - "ensembl_transcript_id"
          - "variation_id"
          - "genome_assembly"
          - "platform"





